basePath: /api/v1
definitions:
  dto.ErrorResponse:
    properties:
      error:
        example: Invalid input
        type: string
    type: object
  dto.LoginInput:
    properties:
      password:
        example: securepassword123
        type: string
      username:
        example: johndoe
        type: string
    type: object
  dto.SignUpInput:
    properties:
      first_name:
        example: John
        type: string
      last_name:
        example: Doe
        type: string
      password:
        example: password123
        type: string
      username:
        example: johndoe
        type: string
    type: object
  dto.UserResponse:
    properties:
      first_name:
        example: John
        type: string
      id:
        example: 1
        type: integer
      last_name:
        example: Doe
        type: string
      username:
        example: johndoe
        type: string
    type: object
host: localhost:3000
info:
  contact: {}
  description: This is a sample API for user management.
  title: Golang API
  version: "1.0"
paths:
  /users/{id}:
    delete:
      description: Deletes a user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Delete a user
      tags:
      - users
  /users/find-many:
    get:
      description: Retrieve list of users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.UserResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Get users
      tags:
      - users
  /users/login:
    post:
      consumes:
      - application/json
      description: Log in with username and password to receive a token
      parameters:
      - description: User login payload
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/dto.LoginInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Authenticate a user
      tags:
      - users
  /users/signup:
    post:
      consumes:
      - application/json
      description: Create a user account with a username and password
      parameters:
      - description: User signup payload
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.SignUpInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Register a new user
      tags:
      - users
  /users/validate:
    get:
      description: Returns the logged-in user's information if the session is valid
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Validate current session
      tags:
      - users
swagger: "2.0"
